
x-app-env: &app-env
  REDIS_ADDR: ${REDIS_ADDR:-redis:6379}
  MINIO_ENDPOINT: ${MINIO_ENDPOINT:-minio:9000}
  MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
  MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
  MINIO_USE_SSL: ${MINIO_USE_SSL:-false}

x-minio-env: &minio-env
  MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}

services:
  app:
    build: .
    environment:
      <<: *app-env
    volumes:
      - ./input-videos:/input-videos
    depends_on:
      - redis
      - minio
    ports:
      - 8080:8080
      - 2112:2112

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      <<: *minio-env
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
  redis-data: